/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/clis/items/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cli Marketplace Detail */
        get: operations["get_cli_marketplace_detail_api_marketplace_clis_items__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/clis/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Popular Cli Marketplace */
        get: operations["popular_cli_marketplace_api_marketplace_clis_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/clis/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Cli Marketplace */
        get: operations["search_cli_marketplace_api_marketplace_clis_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install Marketplace Skill */
        post: operations["install_marketplace_skill_api_marketplace_install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Marketplace Detail */
        get: operations["get_marketplace_detail_api_marketplace_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/items/{item_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Marketplace Document */
        get: operations["get_marketplace_document_api_marketplace_items__item_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/mcp/install-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mcp Install Targets */
        get: operations["get_mcp_install_targets_api_marketplace_mcp_install_targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/mcp/items/{qualified_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mcp Marketplace Detail */
        get: operations["get_mcp_marketplace_detail_api_marketplace_mcp_items__qualified_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/mcp/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Popular Mcp Marketplace */
        get: operations["popular_mcp_marketplace_api_marketplace_mcp_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/mcp/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Mcp Marketplace */
        get: operations["search_mcp_marketplace_api_marketplace_mcp_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Popular Marketplace */
        get: operations["popular_marketplace_api_marketplace_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplace/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Marketplace */
        get: operations["search_marketplace_api_marketplace_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mcp Servers */
        get: operations["list_mcp_servers_api_mcp_servers_get"];
        put?: never;
        /** Install Mcp Server */
        post: operations["install_mcp_server_api_mcp_servers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mcp Server */
        get: operations["get_mcp_server_api_mcp_servers__name__get"];
        put?: never;
        post?: never;
        /** Uninstall Mcp Server */
        delete: operations["uninstall_mcp_server_api_mcp_servers__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers/{name}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Mcp Server */
        post: operations["disable_mcp_server_api_mcp_servers__name__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers/{name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Mcp Server */
        post: operations["enable_mcp_server_api_mcp_servers__name__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers/{name}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile Mcp Server */
        post: operations["reconcile_mcp_server_api_mcp_servers__name__reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers/{name}/set-harnesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Mcp Server Harnesses */
        post: operations["set_mcp_server_harnesses_api_mcp_servers__name__set_harnesses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/unmanaged/adopt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adopt Mcp Server */
        post: operations["adopt_mcp_server_api_mcp_unmanaged_adopt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/unmanaged/by-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Unmanaged By Server */
        get: operations["list_unmanaged_by_server_api_mcp_unmanaged_by_server_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings */
        get: operations["settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/harnesses/{harness}/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Harness Support */
        put: operations["set_harness_support_api_settings_harnesses__harness__support_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_api_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/manage-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manage All Skills */
        post: operations["manage_all_skills_api_skills_manage_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill Detail */
        get: operations["get_skill_detail_api_skills__skill_ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_ref}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Skill */
        post: operations["delete_skill_api_skills__skill_ref__delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_ref}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Skill */
        post: operations["disable_skill_api_skills__skill_ref__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_ref}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Skill */
        post: operations["enable_skill_api_skills__skill_ref__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_ref}/manage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manage Skill */
        post: operations["manage_skill_api_skills__skill_ref__manage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_ref}/set-harnesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Skill Harnesses */
        post: operations["set_skill_harnesses_api_skills__skill_ref__set_harnesses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_ref}/source-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill Source Status */
        get: operations["get_skill_source_status_api_skills__skill_ref__source_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_ref}/unmanage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unmanage Skill */
        post: operations["unmanage_skill_api_skills__skill_ref__unmanage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_ref}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Skill */
        post: operations["update_skill_api_skills__skill_ref__update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slash-commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Slash Commands */
        get: operations["list_slash_commands_api_slash_commands_get"];
        put?: never;
        /** Create Slash Command */
        post: operations["create_slash_command_api_slash_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slash-commands/review/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Slash Command */
        post: operations["import_slash_command_api_slash_commands_review_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slash-commands/review/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Slash Command Review */
        post: operations["resolve_slash_command_review_api_slash_commands_review_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slash-commands/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Slash Command */
        get: operations["get_slash_command_api_slash_commands__name__get"];
        /** Update Slash Command */
        put: operations["update_slash_command_api_slash_commands__name__put"];
        post?: never;
        /** Delete Slash Command */
        delete: operations["delete_slash_command_api_slash_commands__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slash-commands/{name}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Slash Command */
        post: operations["sync_slash_command_api_slash_commands__name__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddMcpServerRequest */
        AddMcpServerRequest: {
            /** Qualifiedname */
            qualifiedName: string;
            /** Sourceharness */
            sourceHarness: string;
        };
        /** AdoptMcpRequest */
        AdoptMcpRequest: {
            /** Harnesses */
            harnesses?: string[] | null;
            /** Name */
            name: string;
            /** Sourceharness */
            sourceHarness?: string | null;
        };
        /** BulkManageFailureResponse */
        BulkManageFailureResponse: {
            /** Error */
            error: string;
            /** Name */
            name: string;
            /** Skillref */
            skillRef: string;
        };
        /** BulkManageResultResponse */
        BulkManageResultResponse: {
            /** Failures */
            failures: components["schemas"]["BulkManageFailureResponse"][];
            /** Managedcount */
            managedCount: number;
            /** Ok */
            ok: boolean;
            /** Skippedcount */
            skippedCount: number;
        };
        /** CliMarketplaceDetailResponse */
        CliMarketplaceDetailResponse: {
            /** Category */
            category?: string | null;
            /** Description */
            description: string;
            /** Githuburl */
            githubUrl?: string | null;
            /** Hasmcp */
            hasMcp: boolean;
            /** Hasskill */
            hasSkill: boolean;
            /** Iconurl */
            iconUrl?: string | null;
            /** Id */
            id: string;
            /** Installcommand */
            installCommand?: string | null;
            /** Isofficial */
            isOfficial: boolean;
            /** Istui */
            isTui: boolean;
            /** Language */
            language?: string | null;
            /** Longdescription */
            longDescription?: string | null;
            /** Marketplaceurl */
            marketplaceUrl: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Sourcetype */
            sourceType?: string | null;
            /** Stars */
            stars?: number | null;
            /** Vendorname */
            vendorName?: string | null;
            /** Websiteurl */
            websiteUrl?: string | null;
        };
        /** CliMarketplaceItemResponse */
        CliMarketplaceItemResponse: {
            /** Category */
            category?: string | null;
            /** Description */
            description: string;
            /** Githuburl */
            githubUrl?: string | null;
            /** Hasmcp */
            hasMcp: boolean;
            /** Hasskill */
            hasSkill: boolean;
            /** Iconurl */
            iconUrl?: string | null;
            /** Id */
            id: string;
            /** Isofficial */
            isOfficial: boolean;
            /** Istui */
            isTui: boolean;
            /** Language */
            language?: string | null;
            /** Marketplaceurl */
            marketplaceUrl: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Sourcetype */
            sourceType?: string | null;
            /** Stars */
            stars?: number | null;
            /** Vendorname */
            vendorName?: string | null;
            /** Websiteurl */
            websiteUrl?: string | null;
        };
        /** CliMarketplacePageResponse */
        CliMarketplacePageResponse: {
            /** Hasmore */
            hasMore: boolean;
            /** Items */
            items: components["schemas"]["CliMarketplaceItemResponse"][];
            /** Nextoffset */
            nextOffset?: number | null;
        };
        /** DisableMcpServerRequest */
        DisableMcpServerRequest: {
            /**
             * Harness
             * @description Harness identifier
             */
            harness: string;
        };
        /** DisableSkillRequest */
        DisableSkillRequest: {
            /**
             * Harness
             * @description Harness identifier
             */
            harness: string;
        };
        /** EnableMcpServerRequest */
        EnableMcpServerRequest: {
            /**
             * Harness
             * @description Harness identifier
             */
            harness: string;
        };
        /** EnableSkillRequest */
        EnableSkillRequest: {
            /**
             * Harness
             * @description Harness identifier
             */
            harness: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HarnessCellResponse */
        HarnessCellResponse: {
            /** Harness */
            harness: string;
            /** Interactive */
            interactive: boolean;
            /** Label */
            label: string;
            /** Logokey */
            logoKey?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "enabled" | "disabled" | "found" | "empty";
        };
        /** HarnessColumnResponse */
        HarnessColumnResponse: {
            /** Harness */
            harness: string;
            /** Installed */
            installed: boolean;
            /** Label */
            label: string;
            /** Logokey */
            logoKey?: string | null;
        };
        /** InstallMarketplaceSkillRequest */
        InstallMarketplaceSkillRequest: {
            /** Installtoken */
            installToken: string;
        };
        /** McpAdoptionIssueResponse */
        McpAdoptionIssueResponse: {
            /** Configpath */
            configPath?: string | null;
            /** Harness */
            harness: string;
            /** Label */
            label: string;
            /** Logokey */
            logoKey?: string | null;
            /** Name */
            name: string;
            /** Payloadpreview */
            payloadPreview?: {
                [key: string]: unknown;
            } | null;
            /** Reason */
            reason: string;
        };
        /** McpApplyConfigResponse */
        McpApplyConfigResponse: {
            /** Failed */
            failed: components["schemas"]["McpMutationFailureResponse"][];
            /** Ok */
            ok: boolean;
            server: components["schemas"]["McpServerSpecResponse"];
            /** Succeeded */
            succeeded: string[];
        };
        /** McpBindingResponse */
        McpBindingResponse: {
            /** Driftdetail */
            driftDetail?: string | null;
            /** Harness */
            harness: string;
            /**
             * State
             * @enum {string}
             */
            state: "managed" | "drifted" | "unmanaged" | "missing";
        };
        /** McpConfigChoiceResponse */
        McpConfigChoiceResponse: {
            /** Configpath */
            configPath?: string | null;
            /** Env */
            env?: components["schemas"]["McpEnvEntryResponse"][];
            /** Label */
            label: string;
            /** Logokey */
            logoKey?: string | null;
            /** Payloadpreview */
            payloadPreview: {
                [key: string]: unknown;
            };
            /** Sourceharness */
            sourceHarness?: string | null;
            /**
             * Sourcekind
             * @enum {string}
             */
            sourceKind: "managed" | "harness";
            spec: components["schemas"]["McpServerSpecResponse"];
        };
        /** McpEnvEntryResponse */
        McpEnvEntryResponse: {
            /** Isenvref */
            isEnvRef: boolean;
            /** Key */
            key: string;
            /** Value */
            value?: string | null;
        };
        /** McpIdentityGroupResponse */
        McpIdentityGroupResponse: {
            canonicalSpec?: components["schemas"]["McpServerSpecResponse"] | null;
            /** Identical */
            identical: boolean;
            marketplaceLink?: components["schemas"]["McpMarketplaceLinkResponse"] | null;
            /** Name */
            name: string;
            /** Sightings */
            sightings: components["schemas"]["McpIdentitySightingResponse"][];
        };
        /** McpIdentitySightingResponse */
        McpIdentitySightingResponse: {
            /** Configpath */
            configPath?: string | null;
            /** Env */
            env?: components["schemas"]["McpEnvEntryResponse"][];
            /** Harness */
            harness: string;
            /** Label */
            label: string;
            /** Logokey */
            logoKey?: string | null;
            /** Payloadpreview */
            payloadPreview: {
                [key: string]: unknown;
            };
            spec: components["schemas"]["McpServerSpecResponse"];
        };
        /** McpInstallTargetResponse */
        McpInstallTargetResponse: {
            /** Harness */
            harness: string;
            /** Label */
            label: string;
            /** Logokey */
            logoKey?: string | null;
            /** Reason */
            reason?: string | null;
            /** Smitheryclient */
            smitheryClient?: string | null;
            /** Supported */
            supported: boolean;
        };
        /** McpInstallTargetsResponse */
        McpInstallTargetsResponse: {
            /** Targets */
            targets: components["schemas"]["McpInstallTargetResponse"][];
        };
        /** McpInventoryColumnResponse */
        McpInventoryColumnResponse: {
            /** Configpresent */
            configPresent: boolean;
            /** Harness */
            harness: string;
            /** Installed */
            installed: boolean;
            /** Label */
            label: string;
            /** Logokey */
            logoKey?: string | null;
            /** Mcpunavailablereason */
            mcpUnavailableReason?: string | null;
            /**
             * Mcpwritable
             * @default true
             */
            mcpWritable: boolean;
        };
        /** McpInventoryEntryResponse */
        McpInventoryEntryResponse: {
            /** Canenable */
            canEnable: boolean;
            /** Displayname */
            displayName: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "managed" | "unmanaged";
            /** Name */
            name: string;
            /** Sightings */
            sightings: components["schemas"]["McpBindingResponse"][];
            spec?: components["schemas"]["McpServerSpecResponse"] | null;
        };
        /** McpInventoryIssueResponse */
        McpInventoryIssueResponse: {
            /** Name */
            name: string;
            /** Reason */
            reason: string;
        };
        /** McpInventoryResponse */
        McpInventoryResponse: {
            /** Columns */
            columns: components["schemas"]["McpInventoryColumnResponse"][];
            /** Entries */
            entries: components["schemas"]["McpInventoryEntryResponse"][];
            /** Issues */
            issues?: components["schemas"]["McpInventoryIssueResponse"][];
        };
        /** McpMarketplaceCapabilityCountsResponse */
        McpMarketplaceCapabilityCountsResponse: {
            /** Prompts */
            prompts: number;
            /** Resources */
            resources: number;
            /** Tools */
            tools: number;
        };
        /** McpMarketplaceConnectionResponse */
        McpMarketplaceConnectionResponse: {
            /** Bundleurl */
            bundleUrl?: string | null;
            /** Configschema */
            configSchema?: {
                [key: string]: unknown;
            } | null;
            /** Deploymenturl */
            deploymentUrl?: string | null;
            /** Kind */
            kind: string;
            /** Runtime */
            runtime?: string | null;
            /** Stdioargs */
            stdioArgs?: string[] | null;
            /** Stdiocommand */
            stdioCommand?: string | null;
            /** Stdiofunction */
            stdioFunction?: string | null;
        };
        /** McpMarketplaceDetailResponse */
        McpMarketplaceDetailResponse: {
            capabilityCounts: components["schemas"]["McpMarketplaceCapabilityCountsResponse"];
            /** Connections */
            connections: components["schemas"]["McpMarketplaceConnectionResponse"][];
            /** Deploymenturl */
            deploymentUrl?: string | null;
            /** Description */
            description: string;
            /** Displayname */
            displayName: string;
            /** Externalurl */
            externalUrl: string;
            /** Iconurl */
            iconUrl?: string | null;
            /** Isremote */
            isRemote: boolean;
            /** Managedname */
            managedName: string;
            /** Prompts */
            prompts: components["schemas"]["McpMarketplacePromptResponse"][];
            /** Qualifiedname */
            qualifiedName: string;
            /** Resources */
            resources: components["schemas"]["McpMarketplaceResourceResponse"][];
            /** Tools */
            tools: components["schemas"]["McpMarketplaceToolResponse"][];
        };
        /** McpMarketplaceItemResponse */
        McpMarketplaceItemResponse: {
            /** Createdat */
            createdAt?: string | null;
            /** Description */
            description: string;
            /** Displayname */
            displayName: string;
            /** Externalurl */
            externalUrl: string;
            /** Homepage */
            homepage?: string | null;
            /** Iconurl */
            iconUrl?: string | null;
            /** Isdeployed */
            isDeployed: boolean;
            /** Isremote */
            isRemote: boolean;
            /** Isverified */
            isVerified: boolean;
            /** Namespace */
            namespace: string;
            /** Qualifiedname */
            qualifiedName: string;
            /** Usecount */
            useCount: number;
        };
        /** McpMarketplaceLinkResponse */
        McpMarketplaceLinkResponse: {
            /** Description */
            description: string;
            /** Displayname */
            displayName: string;
            /** Externalurl */
            externalUrl: string;
            /** Iconurl */
            iconUrl?: string | null;
            /** Isremote */
            isRemote: boolean;
            /** Isverified */
            isVerified: boolean;
            /** Qualifiedname */
            qualifiedName: string;
        };
        /** McpMarketplacePageResponse */
        McpMarketplacePageResponse: {
            /** Hasmore */
            hasMore: boolean;
            /** Items */
            items: components["schemas"]["McpMarketplaceItemResponse"][];
            /** Nextoffset */
            nextOffset?: number | null;
        };
        /** McpMarketplaceParameterResponse */
        McpMarketplaceParameterResponse: {
            /** Default */
            default?: unknown | null;
            /** Description */
            description: string;
            /** Enum */
            enum?: unknown[] | null;
            /** Maxitems */
            maxItems?: number | null;
            /** Maxlength */
            maxLength?: number | null;
            /** Maximum */
            maximum?: number | null;
            /** Minitems */
            minItems?: number | null;
            /** Minlength */
            minLength?: number | null;
            /** Minimum */
            minimum?: number | null;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /** Type */
            type: string;
        };
        /** McpMarketplacePromptArgumentResponse */
        McpMarketplacePromptArgumentResponse: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
        };
        /** McpMarketplacePromptResponse */
        McpMarketplacePromptResponse: {
            /** Arguments */
            arguments: components["schemas"]["McpMarketplacePromptArgumentResponse"][];
            /** Description */
            description: string;
            /** Name */
            name: string;
        };
        /** McpMarketplaceResourceResponse */
        McpMarketplaceResourceResponse: {
            /** Description */
            description: string;
            /** Mimetype */
            mimeType?: string | null;
            /** Name */
            name: string;
            /** Uri */
            uri: string;
        };
        /** McpMarketplaceToolResponse */
        McpMarketplaceToolResponse: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Parameters */
            parameters: components["schemas"]["McpMarketplaceParameterResponse"][];
        };
        /** McpMutationFailureResponse */
        McpMutationFailureResponse: {
            /** Error */
            error: string;
            /** Harness */
            harness: string;
        };
        /** McpServerDetailResponse */
        McpServerDetailResponse: {
            /** Canenable */
            canEnable: boolean;
            /** Configchoices */
            configChoices?: components["schemas"]["McpConfigChoiceResponse"][];
            /** Displayname */
            displayName: string;
            /** Env */
            env?: components["schemas"]["McpEnvEntryResponse"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "managed" | "unmanaged";
            marketplaceLink?: components["schemas"]["McpMarketplaceLinkResponse"] | null;
            /** Name */
            name: string;
            /** Sightings */
            sightings: components["schemas"]["McpBindingResponse"][];
            spec?: components["schemas"]["McpServerSpecResponse"] | null;
        };
        /** McpServerMutationResponse */
        McpServerMutationResponse: {
            /** Ok */
            ok: boolean;
            server: components["schemas"]["McpServerSpecResponse"];
        };
        /** McpServerSpecResponse */
        McpServerSpecResponse: {
            /** Args */
            args?: string[] | null;
            /** Command */
            command?: string | null;
            /** Displayname */
            displayName: string;
            /** Env */
            env?: {
                [key: string]: string;
            } | null;
            /** Headers */
            headers?: {
                [key: string]: string;
            } | null;
            /** Installedat */
            installedAt: string;
            /** Name */
            name: string;
            /** Revision */
            revision: string;
            source: components["schemas"]["McpSourceResponse"];
            /**
             * Transport
             * @enum {string}
             */
            transport: "stdio" | "http" | "sse";
            /** Url */
            url?: string | null;
        };
        /** McpSetHarnessesResultResponse */
        McpSetHarnessesResultResponse: {
            /** Failed */
            failed: components["schemas"]["McpMutationFailureResponse"][];
            /** Ok */
            ok: boolean;
            /** Succeeded */
            succeeded: string[];
        };
        /** McpSourceResponse */
        McpSourceResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "marketplace" | "adopted" | "manual";
            /** Locator */
            locator: string;
        };
        /** McpUnmanagedByServerResponse */
        McpUnmanagedByServerResponse: {
            /** Harnesses */
            harnesses: components["schemas"]["McpUnmanagedHarnessResponse"][];
            /** Issues */
            issues?: components["schemas"]["McpAdoptionIssueResponse"][];
            /** Servers */
            servers: components["schemas"]["McpIdentityGroupResponse"][];
        };
        /** McpUnmanagedHarnessResponse */
        McpUnmanagedHarnessResponse: {
            /** Configpath */
            configPath?: string | null;
            /** Configpresent */
            configPresent: boolean;
            /** Harness */
            harness: string;
            /** Installed */
            installed: boolean;
            /** Label */
            label: string;
            /** Logokey */
            logoKey?: string | null;
            /** Mcpunavailablereason */
            mcpUnavailableReason?: string | null;
            /**
             * Mcpwritable
             * @default true
             */
            mcpWritable: boolean;
        };
        /** OkResponse */
        OkResponse: {
            /** Ok */
            ok: boolean;
        };
        /** ReconcileMcpServerRequest */
        ReconcileMcpServerRequest: {
            /** Harnesses */
            harnesses?: string[] | null;
            /** Sourceharness */
            sourceHarness?: string | null;
            /**
             * Sourcekind
             * @enum {string}
             */
            sourceKind: "managed" | "harness";
        };
        /** SetHarnessSupportRequest */
        SetHarnessSupportRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /** SetMcpServerHarnessesRequest */
        SetMcpServerHarnessesRequest: {
            /**
             * Target
             * @enum {string}
             */
            target: "enabled" | "disabled";
        };
        /** SetSkillHarnessesFailureResponse */
        SetSkillHarnessesFailureResponse: {
            /** Error */
            error: string;
            /** Harness */
            harness: string;
        };
        /** SetSkillHarnessesRequest */
        SetSkillHarnessesRequest: {
            /**
             * Target
             * @description Target state to apply to every interactive harness cell on this skill
             * @enum {string}
             */
            target: "enabled" | "disabled";
        };
        /** SetSkillHarnessesResultResponse */
        SetSkillHarnessesResultResponse: {
            /** Failed */
            failed: components["schemas"]["SetSkillHarnessesFailureResponse"][];
            /** Ok */
            ok: boolean;
            /** Succeeded */
            succeeded: string[];
        };
        /** SettingsHarnessResponse */
        SettingsHarnessResponse: {
            /** Harness */
            harness: string;
            /** Installed */
            installed: boolean;
            /** Label */
            label: string;
            /** Logokey */
            logoKey?: string | null;
            /** Managedlocation */
            managedLocation: string | null;
            /** Supportenabled */
            supportEnabled: boolean;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Harnesses */
            harnesses: components["schemas"]["SettingsHarnessResponse"][];
            storage: components["schemas"]["SettingsStorageResponse"];
        };
        /** SettingsStorageResponse */
        SettingsStorageResponse: {
            /** Configdir */
            configDir: string;
            /** Datadir */
            dataDir: string;
            /** Marketplacecachepath */
            marketplaceCachePath: string;
            /**
             * Platform
             * @enum {string}
             */
            platform: "macos" | "linux";
            /** Settingspath */
            settingsPath: string;
            /** Skillsstorepath */
            skillsStorePath: string;
            /** Statedir */
            stateDir: string;
        };
        /** SkillDetailActionsResponse */
        SkillDetailActionsResponse: {
            /** Candelete */
            canDelete: boolean;
            /** Canmanage */
            canManage: boolean;
            /** Deleteharnesslabels */
            deleteHarnessLabels: string[];
            /** Stopmanagingharnesslabels */
            stopManagingHarnessLabels: string[];
            /** Stopmanagingstatus */
            stopManagingStatus: ("available" | "disabled_no_enabled") | null;
        };
        /** SkillDetailResponse */
        SkillDetailResponse: {
            actions: components["schemas"]["SkillDetailActionsResponse"];
            /** Attentionmessage */
            attentionMessage: string | null;
            /** Description */
            description: string;
            /**
             * Displaystatus
             * @enum {string}
             */
            displayStatus: "Managed" | "Unmanaged";
            /** Documentmarkdown */
            documentMarkdown: string | null;
            /** Harnesscells */
            harnessCells: components["schemas"]["HarnessCellResponse"][];
            /** Locations */
            locations: components["schemas"]["SkillLocationResponse"][];
            /** Name */
            name: string;
            /** Skillref */
            skillRef: string;
            sourceLinks: components["schemas"]["SkillSourceLinksResponse"] | null;
        };
        /** SkillLocationResponse */
        SkillLocationResponse: {
            /** Detail */
            detail: string | null;
            /** Harness */
            harness: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "shared" | "harness";
            /** Label */
            label: string;
            /** Path */
            path: string | null;
            /** Revision */
            revision: string | null;
            /** Scope */
            scope: string | null;
            /** Sourcekind */
            sourceKind: string;
            /** Sourcelocator */
            sourceLocator: string;
        };
        /** SkillRowActionsResponse */
        SkillRowActionsResponse: {
            /** Candelete */
            canDelete: boolean;
            /** Canmanage */
            canManage: boolean;
            /** Canstopmanaging */
            canStopManaging: boolean;
        };
        /** SkillSourceLinksResponse */
        SkillSourceLinksResponse: {
            /** Folderurl */
            folderUrl: string | null;
            /** Repolabel */
            repoLabel: string;
            /** Repourl */
            repoUrl: string;
        };
        /** SkillSourceStatusResponse */
        SkillSourceStatusResponse: {
            /** Updatestatus */
            updateStatus: ("update_available" | "no_update_available" | "no_source_available" | "local_changes_detected") | null;
        };
        /** SkillTableRowResponse */
        SkillTableRowResponse: {
            actions: components["schemas"]["SkillRowActionsResponse"];
            /** Cells */
            cells: components["schemas"]["HarnessCellResponse"][];
            /** Description */
            description: string;
            /**
             * Displaystatus
             * @enum {string}
             */
            displayStatus: "Managed" | "Unmanaged";
            /** Name */
            name: string;
            /** Skillref */
            skillRef: string;
        };
        /** SkillsPageResponse */
        SkillsPageResponse: {
            /** Harnesscolumns */
            harnessColumns: components["schemas"]["HarnessColumnResponse"][];
            /** Rows */
            rows: components["schemas"]["SkillTableRowResponse"][];
            summary: components["schemas"]["SkillsSummaryResponse"];
        };
        /** SkillsSummaryResponse */
        SkillsSummaryResponse: {
            /** Managed */
            managed: number;
            /** Unmanaged */
            unmanaged: number;
        };
        /** SlashCommandDeleteResponse */
        SlashCommandDeleteResponse: {
            /** Ok */
            ok: boolean;
            /** Sync */
            sync: components["schemas"]["SlashSyncEntryResponse"][];
        };
        /** SlashCommandImportRequest */
        SlashCommandImportRequest: {
            /** Name */
            name: string;
            /**
             * Target
             * @enum {string}
             */
            target: "opencode" | "claude" | "cursor" | "codex";
        };
        /** SlashCommandListResponse */
        SlashCommandListResponse: {
            /** Commands */
            commands: components["schemas"]["SlashCommandResponse"][];
            /** Defaulttargets */
            defaultTargets: ("opencode" | "claude" | "cursor" | "codex")[];
            /** Reviewcommands */
            reviewCommands: components["schemas"]["SlashCommandReviewResponse"][];
            /** Storepath */
            storePath: string;
            /** Syncstatepath */
            syncStatePath: string;
            /** Targets */
            targets: components["schemas"]["SlashTargetResponse"][];
        };
        /** SlashCommandMutationRequest */
        SlashCommandMutationRequest: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Prompt */
            prompt: string;
            /** Targets */
            targets?: ("opencode" | "claude" | "cursor" | "codex")[] | null;
        };
        /** SlashCommandMutationResponse */
        SlashCommandMutationResponse: {
            command: components["schemas"]["SlashCommandResponse"] | null;
            /** Ok */
            ok: boolean;
            /** Sync */
            sync: components["schemas"]["SlashSyncEntryResponse"][];
        };
        /** SlashCommandResolveRequest */
        SlashCommandResolveRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "restore_managed" | "adopt_target" | "remove_binding";
            /** Name */
            name: string;
            /**
             * Target
             * @enum {string}
             */
            target: "opencode" | "claude" | "cursor" | "codex";
        };
        /** SlashCommandResponse */
        SlashCommandResponse: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Prompt */
            prompt: string;
            /** Synctargets */
            syncTargets: components["schemas"]["SlashSyncEntryResponse"][];
        };
        /** SlashCommandReviewResponse */
        SlashCommandReviewResponse: {
            /** Actions */
            actions: ("import" | "restore_managed" | "adopt_target" | "remove_binding")[];
            /** Canimport */
            canImport: boolean;
            /** Commandexists */
            commandExists: boolean;
            /** Description */
            description: string;
            /** Error */
            error?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "unmanaged" | "drifted" | "missing";
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Prompt */
            prompt: string;
            /** Reviewref */
            reviewRef: string;
            /**
             * Target
             * @enum {string}
             */
            target: "opencode" | "claude" | "cursor" | "codex";
            /** Targetlabel */
            targetLabel: string;
        };
        /** SlashCommandUpdateRequest */
        SlashCommandUpdateRequest: {
            /** Description */
            description: string;
            /** Prompt */
            prompt: string;
            /** Targets */
            targets?: ("opencode" | "claude" | "cursor" | "codex")[] | null;
        };
        /** SlashSyncEntryResponse */
        SlashSyncEntryResponse: {
            /** Error */
            error?: string | null;
            /** Path */
            path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "synced" | "removed" | "not_selected" | "blocked_manual_file" | "blocked_modified_file" | "missing" | "drifted" | "failed";
            /**
             * Target
             * @enum {string}
             */
            target: "opencode" | "claude" | "cursor" | "codex";
        };
        /** SlashSyncRequest */
        SlashSyncRequest: {
            /** Targets */
            targets?: ("opencode" | "claude" | "cursor" | "codex")[] | null;
        };
        /** SlashTargetResponse */
        SlashTargetResponse: {
            /** Available */
            available: boolean;
            /** Defaultselected */
            defaultSelected: boolean;
            /** Docsurl */
            docsUrl: string;
            /** Enabled */
            enabled: boolean;
            /** Fileglob */
            fileGlob: string;
            /**
             * Id
             * @enum {string}
             */
            id: "opencode" | "claude" | "cursor" | "codex";
            /** Invocationprefix */
            invocationPrefix: string;
            /** Label */
            label: string;
            /** Outputdir */
            outputDir: string;
            /**
             * Renderformat
             * @enum {string}
             */
            renderFormat: "frontmatter_markdown" | "cursor_plaintext";
            /** Rootpath */
            rootPath: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "global" | "project";
            /** Supportnote */
            supportNote?: string | null;
            /** Supportsfrontmatter */
            supportsFrontmatter: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_cli_marketplace_detail_api_marketplace_clis_items__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliMarketplaceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    popular_cli_marketplace_api_marketplace_clis_popular_get: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliMarketplacePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_cli_marketplace_api_marketplace_clis_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliMarketplacePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_marketplace_skill_api_marketplace_install_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallMarketplaceSkillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_marketplace_detail_api_marketplace_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_marketplace_document_api_marketplace_items__item_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mcp_install_targets_api_marketplace_mcp_install_targets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpInstallTargetsResponse"];
                };
            };
        };
    };
    get_mcp_marketplace_detail_api_marketplace_mcp_items__qualified_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qualified_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpMarketplaceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    popular_mcp_marketplace_api_marketplace_mcp_popular_get: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpMarketplacePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_mcp_marketplace_api_marketplace_mcp_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number | null;
                offset?: number;
                remote?: boolean | null;
                verified?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpMarketplacePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    popular_marketplace_api_marketplace_popular_get: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_marketplace_api_marketplace_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mcp_servers_api_mcp_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpInventoryResponse"];
                };
            };
        };
    };
    install_mcp_server_api_mcp_servers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMcpServerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mcp_server_api_mcp_servers__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uninstall_mcp_server_api_mcp_servers__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpSetHarnessesResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_mcp_server_api_mcp_servers__name__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisableMcpServerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_mcp_server_api_mcp_servers__name__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnableMcpServerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_mcp_server_api_mcp_servers__name__reconcile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconcileMcpServerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpApplyConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_mcp_server_harnesses_api_mcp_servers__name__set_harnesses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMcpServerHarnessesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpSetHarnessesResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adopt_mcp_server_api_mcp_unmanaged_adopt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdoptMcpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpApplyConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_unmanaged_by_server_api_mcp_unmanaged_by_server_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpUnmanagedByServerResponse"];
                };
            };
        };
    };
    settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    set_harness_support_api_settings_harnesses__harness__support_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                harness: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetHarnessSupportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsPageResponse"];
                };
            };
        };
    };
    manage_all_skills_api_skills_manage_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkManageResultResponse"];
                };
            };
        };
    };
    get_skill_detail_api_skills__skill_ref__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_skill_api_skills__skill_ref__delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_skill_api_skills__skill_ref__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisableSkillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_skill_api_skills__skill_ref__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnableSkillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manage_skill_api_skills__skill_ref__manage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_skill_harnesses_api_skills__skill_ref__set_harnesses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSkillHarnessesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetSkillHarnessesResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_source_status_api_skills__skill_ref__source_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSourceStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unmanage_skill_api_skills__skill_ref__unmanage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_skill_api_skills__skill_ref__update_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_slash_commands_api_slash_commands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlashCommandListResponse"];
                };
            };
        };
    };
    create_slash_command_api_slash_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlashCommandMutationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlashCommandMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_slash_command_api_slash_commands_review_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlashCommandImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlashCommandMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_slash_command_review_api_slash_commands_review_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlashCommandResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlashCommandMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slash_command_api_slash_commands__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlashCommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_slash_command_api_slash_commands__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlashCommandUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlashCommandMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_slash_command_api_slash_commands__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlashCommandDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_slash_command_api_slash_commands__name__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlashSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlashCommandMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
